language: ruby
rvm:
 - 2.1
 - 2.2
cache: bundler
bundler_args: --without production
before_script:
  - cp config/database.travis.yml config/database.yml
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake db:migrate RAILS_ENV=test

